version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-calendar-mcp
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV:-production}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - MCP_SERVER_ID=${MCP_SERVER_ID:-google-calendar-mcp}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-Google Calendar Integration}
      - MCP_SERVER_DESCRIPTION=${MCP_SERVER_DESCRIPTION:-Retrieves and manages Google Calendar events}
    volumes:
      - ./token.json:/app/token.json
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
